---

something: xyz
ansible_connection: ssh
ansible_user: root
ansible_ssh_pass: root
ansible_port: 21
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

