- hosts: kops
  gather_facts: false
  become: yes
  tasks:

   - name: install remote apt deps
     apt:
       name: "{{ item }}"
       state: present
     with_items:
       - apt-transport-https
       - ca-certificates
       - gnupg2
       - software-properties-common

   - name: Get Latest Version of kops
     shell: curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4
     register: kops_version

   - name: set join command
     set_fact:
       kops_ver: "{{ kops_version.stdout_lines[0] }}"

   - name: Download Kops binaries
     get_url:
       url: "https://github.com/kubernetes/kops/releases/download/{{kops_ver}}/kops-linux-amd64"
       dest: /usr/local/bin/kops
       owner: root
       group: root
       mode: 0755
       force: yes

   - name: Get Latest Version of kubectl
     shell: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
     register: kubectl_version

   - name: set join command
     set_fact:
       kubectl_ver: "{{ kubectl_version.stdout_lines[0] }}"

   - name: install kubectl
     get_url:
       url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_ver }}/bin/linux/amd64/kubectl"
       dest: /usr/local/bin/kubectl
       owner: root
       group: root
       mode: 0755
       force: yes

