- hosts: kops
  gather_facts: false
  become: yes
  tasks:

   - name: install remote apt deps
     apt:
       name: "{{ item }}"
       state: present
     with_items:
       - apt-transport-https
       - ca-certificates
       - gnupg2
       - software-properties-common

   - name: add Docker apt-key
     apt_key:
       url: https://download.docker.com/linux/debian/gpg
       state: present

   - name: add Docker's APT repository
     apt_repository:
      repo: deb https://download.docker.com/linux/debian stretch stable
      state: present
      filename: 'docker'

   - name: install Docker
     apt:
       name: docker-ce
       state: present
       update_cache: true

   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     apt:
       name: kubelet
       state: present
       update_cache: true

   - name: Get Latest Version of kops
     shell: curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4
     register: kops_version

   - name: set join command
     set_fact:
       kops_ver: "{{ kops_version.stdout_lines[0] }}"

   - name: Download Kops binaries
     get_url:
       url: "https://github.com/kubernetes/kops/releases/download/{{kops_ver}}/kops-linux-amd64"
       dest: /usr/local/bin/kops
       owner: root
       group: root
       mode: 0755
       force: yes

   - name: install kubectl
     apt:
       name: kubectl
       state: present
       force: yes
