- hosts: kops
  gather_facts: false
  become: yes
  tasks:

    - name: Changing Hostname to kops
      replace:
        path: /etc/hostname
        regexp: 'ip-.*$'
        replace: "kops"
        backup: yes
      register: reboot_req

    - name: Reboot immediately if there was a change in reboot_req.
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: reboot_req is changed

    - name: Wait for the reboot to complete if there was a change in reboot_req.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: reboot_req is changed

    - name: Check if machine is On
      shell: hostname
      register: op_join

    - name: op join command
      set_fact:
        op: "{{ op_join.stdout_lines[0] }}"

    - name: Print Hostname of host machine
      debug:
        msg: "{{ op }}"

